# -*- coding: utf-8 -*-
"""B2P_clean_final_output.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M62TXq9hqcTZsbmGBVk-G6zUn38S4ZuP
"""

# Imports
import numpy as np
import pandas as pd
from datetime import date
import json


# Load data
df = pd.read_csv(
    "https://raw.githubusercontent.com/Lambda-School-Labs/Labs25-Bridges_to_Prosperity-TeamB-ds/jakekrafczyk-patch-1/data/edit/B2P_Rwanda_MatchedIds.csv"
)
df.drop("Unnamed: 0", 1, inplace=True)


# replace NaN
"""
str : ?
int : 0
float : 0
"""

df["Cell"] = df["Cell"].replace(np.nan, "?")
df["Project Sub-Stage"] = df["Project Sub-Stage"].replace(np.nan, "?")
df["Bridge Type"] = df["Bridge Type"].replace(np.nan, "?")
df["GPS (Latitude)"] = df["GPS (Latitude)"].replace(np.nan, 0)
df["GPS (Longitude)"] = df["GPS (Longitude)"].replace(np.nan, 0)
df["Community Served 1"] = df["Community Served 1"].replace(np.nan, "?")
df["Community Served 2"] = df["Community Served 2"].replace(np.nan, "?")
df["Community Served 3"] = df["Community Served 3"].replace(np.nan, "?")
df["Community Served 4"] = df["Community Served 4"].replace(np.nan, "?")
df["Community Served 5"] = df["Community Served 5"].replace(np.nan, "?")
df["Village"] = df["Village"].replace(np.nan, "?")
df["Sector_ID"] = df["Sector_ID"].replace(np.nan, 0)
df["Cell_ID"] = df["Cell_ID"].replace(np.nan, 0)
df["Village_ID"] = df["Village_ID"].replace(np.nan, 0)


# converting dtypes
df["Span (m)"] = df["Span (m)"].astype(int)
df["Individuals Directly Served"] = df["Individuals Directly Served"].astype(int)
df["Dist_ID"] = df["Dist_ID"].astype(int)
df["Sector_ID"] = df["Sector_ID"].astype(int)
df["Cell_ID"] = df["Cell_ID"].astype(int)
df["Village_ID"] = df["Village_ID"].astype(int)


df["Dist_ID"] = df["Dist_ID"].astype(str)
df["Sector_ID"] = df["Sector_ID"].astype(str)
df["Cell_ID"] = df["Cell_ID"].astype(str)
df["Village_ID"] = df["Village_ID"].astype(str)


df["Sector_ID"] = df["Sector_ID"].replace("0", "?")
df["Cell_ID"] = df["Cell_ID"].replace("0", "?")
df["Village_ID"] = df["Village_ID"].replace("0", "?")


# reordering df
column_order = [
    "Country",
    "Province",
    "District",
    "Dist_ID",
    "Sector",
    "Sector_ID",
    "Cell",
    "Cell_ID",
    "Village",
    "Village_ID",
    "Bridge Site Name",
    "Project Code",
    "Bridge Type",
    "Project Stage",
    "Project Sub-Stage",
    "Individuals Directly Served",
    "Span (m)",
    "GPS (Latitude)",
    "GPS (Longitude)",
    "Community Served 1",
    "Community Served 2",
    "Community Served 3",
    "Community Served 4",
    "Community Served 5",
    "Community_served",
    "Form: Form Name",
    "CaseSafeID Form",
    "Bridge Opportunity: Opportunity ID",
]
df_ordered = df.reindex(columns=column_order)

# Renaming Column
df_ordered = df_ordered.rename(columns={"Community_served": "Communities_Served"})


# Split "Communities_Served" entries
df_ordered["Communities_Served"] = df_ordered["Communities_Served"].str.split()


## Data Output in .csv

# Getting current date to keep track of dataset changes
date = date.today()
print("Today's date:", date)

# site_assessment
filename_df_ordered = f"B2P_Rwanda_Sites+IDs_full_{date}.csv"

# Dataframe to .csv conversion
df_ordered.to_csv(filename_df_ordered)
